trigger:
  branches:
    include:
      - main
  tags:
    include:
      - v*
  paths:
    exclude:
      - "*"

pr:
  - "*"

pool:
  vmImage: "ubuntu-latest"

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

jobs:
  - job: RunTests
    displayName: "Run Tests"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "18.x"
        displayName: "Install Node.js"

      - task: Cache@2
        inputs:
          key: 'npm | "$(Agent.OS)" | package-lock.json'
          restoreKeys: 'npm | "$(Agent.OS)"'
          path: $(npm_config_cache)
        displayName: "Cache npm"

      - script: npm ci
        displayName: "Install dependencies"

      - script: npm run lint
        displayName: Linting

      - script: npm run prettier:ci
        displayName: Prettier

      - script: npm run test
        displayName: Unit tests

      - script: npm run build
        displayName: "Build"

      - script: npm pack
        displayName: "Pack"

      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: "$(Build.ArtifactStagingDirectory)"
          artifact: "package"
          publishLocation: "pipeline"
        condition: and(succeeded(), eq(variables['Build.Reason'], 'individualCI'))
        displayName: "Publish Artifact: package"

  - job: PublishToNpm
    displayName: "Publish to npm"
    condition: and(succeeded(), eq(variables['Build.Reason'], 'individualCI'), ne(variables['Build.SourceBranch'], 'refs/tags/*'))
    steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: "npmPackage"
          downloadPath: "$(System.DefaultWorkingDirectory)"
        displayName: "Download npm package artifact"

      - bash: |
          echo "Publishing to npm..."
          tarball=$(ls *.tgz)
          npm publish $tarball --access private
        displayName: "Publish to npm"
        env:
          NODE_AUTH_TOKEN: $(NpmAuthToken)
