name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: npm install
        run: |
          npm ci
        env:
          CI: true

      - name: npm lint
        run: |
          npm run lint
        env:
          CI: true

      - name: check format
        run: |
          npm run prettier:ci
        env:
          CI: true

      - name: npm build
        run: |
          npm run build
        env:
          CI: true
          VITE_RC_ENDPOINT: https://api.revenuecat.com
